language: node_js
node_js:
  - "14"
cache:
directories:
  - node_modules
  - .next
branches:
  only:
  - main
script:
  - npm run test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: out
  github_token: $GITHUB_TOKEN
  target_branch: gh-pages
  keep_history: true
  on:
    branch: main